// Generated by emit_tokens.py from brand.json — do not edit.
// Every colour, font and size a deck script uses comes from here.
const path = require("path");
const T = {
  "register": "read",
  "fonts": {
    "heading": "Calibri",
    "body": "Calibri"
  },
  "colours": {
    "ink": "F0F4F8",
    "paper": "0B1220",
    "accent": "00D084",
    "muted": "94A3B8"
  },
  "palette": {
    "accent": "00D084",
    "accent2": "00796B",
    "accent3": "4BACC6",
    "accent4": "8064A2",
    "accent5": "F79646",
    "accent6": "C0504D",
    "ink": "F0F4F8",
    "paper": "0B1220",
    "muted": "94A3B8"
  },
  "scale": {
    "display": 72.0,
    "title": 48.0,
    "h1": 32.0,
    "body": 18.0,
    "caption": 12.0
  },
  "slide": {
    "w": 13.333,
    "h": 7.5
  },
  "margins": {
    "x": 0.667,
    "top": 0.6,
    "bottom": 0.6
  },
  "shape": {
    "corner": "rounded",
    "hairline_pt": 1.0
  }
};
T.loadPptxgen = function () {
  try { return require("pptxgenjs"); } catch (err) {
    return require(path.join(__dirname, "node_modules", "pptxgenjs"));
  }
};
module.exports = T;
